name: CI
on:
  push:
    branches:
      - master
jobs:
  build-dita-and-deploy-netlify:
    name: Build DITA WebHelp Responsive
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      
      - name: Extract license from secrets
        run: |
          echo "$OPE_LICENSE" > licensekey.txt
        env:
          OPE_LICENSE: ${{ secrets.OPE_LICENSE }}
        
      - name: Download the engine
        run: |
            sudo wget "http://mirror.oxygenxml.com/maven-nightly/com/oxygenxml/oxygen-publishing-engine-3.x/25.0-SNAPSHOT/oxygen-publishing-engine-3.x-25.0-SNAPSHOT-package-full.zip"
            sudo apt-get install unzip
            sudo unzip oxygen-publishing-engine-3.x-25.0-SNAPSHOT-package-full.zip
            sudo cp licensekey.txt oxygen-publishing-engine-3.x/licensekey.txt
            
      - name: Build WebHelp Responsive
        run: |
            cd oxygen-publishing-engine-3.x/bin
            sudo ./dita --input=../../doc/project-documentation/search-service-doc.ditamap --format=webhelp-responsive -Dwebhelp.publishing.template=../../templates/webhelp-documentation-template --output=../../doc/project-documentation/out
            
      - name: 'Deploy to Netlify'
      - uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_DEPLOY_TO_PROD: true
